# Generated by Django 4.1.1 on 2022-09-28 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='items',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='items',
            table='items',
        ),
    ]
