# Generated by Django 4.1.1 on 2022-09-27 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_users_login_users_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lists',
            fields=[
                ('id_list', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to='users.users')),
            ],
            options={
                'db_table': 'lists',
                'managed': True,
            },
        ),
    ]
